import type { Metadata } from "next";

import "./globals.css";

import SideNavigation from "./components/sideNav/SideNavigation";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Plant App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="page_main">
          <SideNavigation />
          <main>
            <Footer />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
