import type { Metadata } from "next";

import "./globals.css";

import SideNavigation from "./components/sideNav/SideNavigation";

export const metadata: Metadata = {
  title: "Plant App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SideNavigation />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
